# @format

project:
  title: "boxplot"

format:
  html:
    theme:
      light: cosmo # cerulean lumen flatly
      dark: cyborg
    number-sections: false
    embed-resources: true
  pdf:
    toc: false
execute:
  freeze: auto
